#!/usr/bin/env bash
# APKAM enrollment for NoPorts on SR Linux: cuts new, scope-limited keys for
# this router ON the router — no atKeys file is ever copied to it.
#
# Run from the SR Linux bash shell as root, after editing
# /etc/opt/sshnpd/sshnpd.env:
#
#   sudo /opt/sshnpd/onboard-sshnpd.sh <passcode>
#
# where <passcode> is an OTP or SPP generated by an administrator with an
# already-authorized key for the device atSign, e.g. on their machine:
#
#   at_activate otp -a @mydevice          # one-time passcode, or
#   at_activate spp -a @mydevice -s <passcode> -e 1d
#
# While this script waits, the administrator approves the request:
#
#   at_activate approve -a @mydevice --arx sshnpd --drx <device-name>
#
# On approval the APKAM keys are written to the KEY_FILE path used by
# run-sshnpd.sh, and the sshnpd app can be started.
set -euo pipefail

ENV_FILE=/etc/opt/sshnpd/sshnpd.env
if [ ! -f "$ENV_FILE" ]; then
    echo "onboard: $ENV_FILE not found; copy sshnpd.env.example and edit it" >&2
    exit 1
fi
# shellcheck disable=SC1090
source "$ENV_FILE"

: "${DEVICE_ATSIGN:?set DEVICE_ATSIGN in $ENV_FILE}"
: "${DEVICE_NAME:?set DEVICE_NAME in $ENV_FILE}"
KEY_FILE="${KEY_FILE:-/etc/opt/sshnpd/keys/${DEVICE_ATSIGN}_key.atKeys}"
ROOT_SERVER="${ROOT_SERVER:-root.atsign.org}"
AT_ACTIVATE_BIN="${AT_ACTIVATE_BIN:-/usr/local/bin/at_activate}"

PASSCODE="${1:-}"
if [ -z "$PASSCODE" ]; then
    read -r -s -p "Enrollment passcode (OTP/SPP) for ${DEVICE_ATSIGN}: " PASSCODE
    echo
fi

if [ -f "$KEY_FILE" ]; then
    echo "onboard: $KEY_FILE already exists; delete it first to re-enroll" >&2
    exit 1
fi

export HOME=/var/opt/sshnpd
mkdir -p "$HOME" "$(dirname "$KEY_FILE")"

echo "Requesting APKAM enrollment for ${DEVICE_ATSIGN} (device ${DEVICE_NAME})..."
echo "Approve it from an authorized client, e.g.:"
echo "  at_activate approve -a ${DEVICE_ATSIGN} --arx sshnpd --drx ${DEVICE_NAME}"

# Enrollment traffic follows the same egress path as the daemon: the
# srbase-mgmt namespace, honoring ROOT_SERVER (proxy:host:443 form included).
ip netns exec srbase-mgmt "$AT_ACTIVATE_BIN" enroll \
    --atsign "$DEVICE_ATSIGN" \
    --root-server "$ROOT_SERVER" \
    --passcode "$PASSCODE" \
    --app sshnpd \
    --device "$DEVICE_NAME" \
    --namespaces "sshnp:rw,sshrvd:rw" \
    --keys "$KEY_FILE"

chmod 0600 "$KEY_FILE"
echo
echo "Enrollment complete; APKAM keys written to $KEY_FILE"
echo "Start the daemon from the SR Linux CLI:"
echo "  tools system app-management application sshnpd restart"
