#!/usr/bin/env bash
# APKAM enrollment for NoPorts on SR Linux: cuts new, scope-limited keys for
# this router ON the router — no atKeys file is ever copied to it.
#
# Configure /noports first (device-atsign, device-name, root-server if using
# a proxy), then run from the SR Linux bash shell as root:
#
#   sudo /opt/noports/onboard-noports.sh <passcode>
#
# where <passcode> is an OTP or SPP generated by an administrator with an
# already-authorized key for the device Atsign, e.g. on their machine:
#
#   at_activate otp -a @mydevice          # one-time passcode, or
#   at_activate spp -a @mydevice -s <passcode> -e 1d
#
# While this script waits, the administrator approves the request:
#
#   at_activate approve -a @mydevice --arx noports --drx <device-name>
#
# On approval the APKAM keys are written to the configured key-file path and
# the agent (which polls for the keys) starts sshnpd automatically.
set -euo pipefail

AT_ACTIVATE_BIN="${AT_ACTIVATE_BIN:-/usr/local/bin/at_activate}"

# Pull the /noports configuration from the running datastore, so onboarding
# uses exactly what the daemon will use. "sr_cli info flat" emits
# "set / noports <leaf> <value>" lines.
get_leaf() {
    sr_cli "info flat from running /noports $1" 2>/dev/null \
        | awk -v leaf="$1" '$0 ~ "noports "leaf" " {print $NF; exit}' \
        | tr -d '"'
}

DEVICE_ATSIGN="${DEVICE_ATSIGN:-$(get_leaf device-atsign)}"
DEVICE_NAME="${DEVICE_NAME:-$(get_leaf "device name")}"
ROOT_SERVER="${ROOT_SERVER:-$(get_leaf root-server)}"
KEY_FILE="${KEY_FILE:-$(get_leaf key-file)}"
ROOT_SERVER="${ROOT_SERVER:-root.atsign.org}"
KEY_FILE="${KEY_FILE:-/etc/opt/noports/keys/device.atKeys}"

if [ -z "$DEVICE_ATSIGN" ] || [ -z "$DEVICE_NAME" ]; then
    echo "onboard: device-atsign / device name not configured." >&2
    echo "Configure first, e.g. from the SR Linux CLI:" >&2
    echo "  enter candidate" >&2
    echo "  set / noports device-atsign @mydevice" >&2
    echo "  set / noports device name srl-router-1" >&2
    echo "  set / noports access managers [ @manager ]" >&2
    echo "  set / noports admin-state enable" >&2
    echo "  commit now" >&2
    exit 1
fi

PASSCODE="${1:-}"
if [ -z "$PASSCODE" ]; then
    read -r -s -p "Enrollment passcode (OTP/SPP) for ${DEVICE_ATSIGN}: " PASSCODE
    echo
fi

if [ -f "$KEY_FILE" ]; then
    echo "onboard: $KEY_FILE already exists; delete it first to re-enroll" >&2
    exit 1
fi

export HOME=/var/opt/noports
mkdir -p "$HOME" "$(dirname "$KEY_FILE")"

echo "Requesting APKAM enrollment for ${DEVICE_ATSIGN} (device ${DEVICE_NAME})..."
echo "Approve it from an authorized client, e.g.:"
echo "  at_activate approve -a ${DEVICE_ATSIGN} --arx noports --drx ${DEVICE_NAME}"

# Enrollment traffic follows the same egress path as the daemon: the
# srbase-mgmt namespace, honoring root-server (proxy:host:443 form included).
ip netns exec srbase-mgmt "$AT_ACTIVATE_BIN" enroll \
    --atsign "$DEVICE_ATSIGN" \
    --root-server "$ROOT_SERVER" \
    --passcode "$PASSCODE" \
    --app noports \
    --device "$DEVICE_NAME" \
    --namespaces "sshnp:rw,sshrvd:rw" \
    --keys "$KEY_FILE"

chmod 0600 "$KEY_FILE"
echo
echo "Enrollment complete; APKAM keys written to $KEY_FILE"
echo "The noports agent will detect the keys and start sshnpd within ~15s."
echo "Check from the SR Linux CLI:  info from state / noports state"
